---
- name: Hello world exmaple
  hosts: all
  vars_files: 
    - vars/hello-world.yml
  tasks:
  - name: Print hello world
    shell: echo "Hello World from {{ location }}"
    register: std_out

  - name: print out standard output
    debug:
      var: std_out.stdout_lines

  - name: Create a hello world file
    copy: 
      content: "hello world from {{ location }}\n" 
      dest: /tmp/helloworld.txt